### ISSUE TITLE
Programieren aller Effekte

### ISSUE THREAD

**Issue by medem100** [medem100/C4L_Applet#15]
- [x] Scanoperator-Effekte
- [x]  Rainbow
- [x] Lauflicht
- [x] Triangle

**Comment by medem100** [comment]
Ja ich hätte gern mehr Effekte als Rainbow :) 
Vor allem alle die auf dem Scan Operateur sind

**Comment by medem100** [comment]
Ich mach das gerade mit der App und irgendwie hat die Bestätigung nicht so geklappt das er den Kommentar gessätzt hat 😂

**Comment by medem100** [comment]
Lauflicht bitte ! :)

**Comment by medem100** [comment]
Ne art Stroboskop Farbwechsel bei jedem aufblinken ne neue farbe

**Comment by medem100** [comment]
Buntes Lauflicht :) jeder in ner anderen Farbe :)

**Comment by Simoris** [comment]
Du hast gerade dreimal den gleichen Effekt in verschiedenen Kombinationen mit bisherigen Effekten beschrieben.

**Comment by medem100** [comment]
Wäre vielleicht cool dafür ne Art short Cut zu haben ? 
Also auch wen es ne Kombination ist sie vielleicht unter einer Idee aufrufen zu können ? Oder macht das mit der jetzt Struktur überhaupt Sinn ? Arbeiten ja mit ner Liste ?

**Comment by Simoris** [comment]
Die aktuelle Struktur ist darauf ausgelegt möglichst viel zu können. An irgendeiner Stelle wird es sicherlich eine Art Favoritenliste mit "sinnvollen" Effektkombinationen und -konfigurationen geben müssen

**Comment by medem100** [comment]
OK :)

**Comment by medem100** [comment]
Idee : 
Ein effeck Farbe faded ein . Farbe faded aus . Bleibt Dunkel.... Farbe faded wieder ein 

Oder kam man das wo raus basteln ?
